@host = http://localhost:5037
POST {{host}}/products/form
Content-Type: application/x-www-form-urlencoded

id=213
&name=Oval Marble Pattern Bohemian Dangle Earrings
&price=2.18
&description=Creative Oval Marble Pattern Synthetic Gemstone Decor Bohemian Pendant Earrings Zinc Alloy Silvery Jewelry
&smallImage=2c40aad6-e0b7-4bc3-a718-18b6036f3ea3.webp,5a5a041f-c0a2-471a-987a-a0d7ec42d1b7.webp,85008044-2225-4b2f-97ff-ec03576cab0b.webp,9d37f961-7006-49f8-9bef-5482b58b0467.webp,bce4e0af-a7b8-44d3-ad6e-fa158d83068d.webp
&availability=10
&slug=creative-oval-marble-pattern-bohemian-dangle-earrings
&category=earrings
