@host = http://localhost:5037
@id = 123

PUT {{host}}/admin/form/{{id}}
Content-Type: application/x-www-form-urlencoded

id=213
&name=Winter Long Geometric Sweater Chain Fringe Leaf Resin Necklace
&price=6.89
&description=Creative Oval Marble Pattern Synthetic Gemstone Decor Bohemian Pendant Earrings Zinc Alloy Silvery Jewelry
&smallImage=1d443aaf-d8cc-4fd8-8e87-75e2585cccc9.webp
&availability=10
&slug=creative-oval-marble-pattern-bohemian-dangle-earrings
&category=earrings